@include('components.animelist')
@include('components.spinkit')
@include('components.batchimport')
@include('components.vselect')
@include('components.togglebutton')
@include('components.paginavigator')
